source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CQGoogleDirections_Example', :exclusive => true do
  pod "CQGoogleDirections", :path => "../"
end

target 'CQGoogleDirections_Tests', :exclusive => true do
  pod "CQGoogleDirections", :path => "../"

  
end
